# Generated by Django 3.0.7 on 2020-06-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_cliente', 'Es un cliente'), ('is_admin', 'Es un admin'))},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='usuario',
        ),
    ]
