# Generated by Django 3.0.7 on 2020-06-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='app1.Venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='app1.Producto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.CASCADE, to='app1.Producto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='app1.Producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
