# Generated by Django 3.0.7 on 2020-06-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200626_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='orden',
            field=models.ManyToManyField(blank=True, null=True, to='app1.OrdenCompra'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Venta'),
        ),
    ]
