# Generated by Django 3.0.7 on 2020-06-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200626_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='cantidad_producto',
            field=models.IntegerField(),
        ),
    ]
