# Generated by Django 3.0.7 on 2020-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200627_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
