# Generated by Django 3.0.7 on 2020-07-10 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_ordencompra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='hora_act',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de actualizacion'),
        ),
    ]
